package no.uib.inf101.model.tetromino;

/**
 * A Interface representing a TetrominoFactory responsible for generating Tetromino objects.
 * @author Alper.Yarenbasi
 */
public interface TetrominoFactory {

    /**
     * Generates the next Tetromino.
     *
     * @return The next Tetromino object generated by the factory.
     */
    Tetromino getNext();
}
